# Generated by Django 5.2.4 on 2025-08-19 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aprendices', '0002_alter_aprendiz_options_remove_aprendiz_programa_and_more'),
        ('instructores', '0001_initial'),
        ('programas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_horas', models.PositiveIntegerField(help_text='Cantidad de horas de asistencia del aprendiz', verbose_name='Horas de Asistencia')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones sobre la asistencia', null=True, verbose_name='Observaciones')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha Fin')),
                ('Estado', models.CharField(choices=[('SI', 'asistio'), ('NO', 'no asistio')], default='SI', max_length=2, verbose_name='Estado')),
                ('Codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programas.programa', verbose_name='Código del Programa')),
                ('aprendiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aprendices.aprendiz', verbose_name='Aprendiz')),
                ('instructor', models.ForeignKey(help_text='Instructor que dicto la clase', on_delete=django.db.models.deletion.CASCADE, to='instructores.instructor', verbose_name='Instructor')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
            },
        ),
    ]
